rtmUrl: https://slack.com/api/rtm.start?token={token}&simple_latest&no_unreads
logging.level.kotlin: DEBUG
logging.level.me.ramswaroop: DEBUG

spring:
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    url: ${jdbcUrl:redacted}
    username: ${jdbcUsername:redacted}
    password: ${jdbcPassword:redacted}
    driver-class-name: org.postgresql.Driver

slackBotToken: ${slackBotToken:redacted}
omdbApiKey: ${omdbApiKey:redacted}
tmdbApiKey: ${tmdbApiKey:redacted}
spring.autoconfigure.exclude:
  - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration