rtmUrl: https://slack.com/api/rtm.start?token={token}&simple_latest&no_unreads
logging.level.kotlin: INFO


spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:

        use_sql_comments: false
        format_sql: false
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          batch_size: 100
          order_inserts: true
          order_updates: true
          batch_versioned_data: true

  datasource:
    url: ${jdbcUrl:redacted}
    username: ${jdbcUsername:redacted}
    password: ${jdbcPassword:redacted}
    driver-class-name: org.postgresql.Driver

management:
  endpoint:
    health:
      show-details: always
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus

feign:
  client:
    config:
      default:
        loggerLevel: full
logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    kombient: INFO
    kombient.movies.tmdb.TmdbClient: DEBUG
    kombient.movies.imdb.ImdbClient: DEBUG


dns.health.hostnames: google.com,postgres

imdb:
  similarityscore: 0.85
  channel: '#diablo_iii'
  userconfig:
    Gweli: ur24140816
    Warc: ur24043276
    Tommy: ur36033733
    Molcsa: ur28253056
    Shank: ur32966271
    Eri: ur24012933
    Bensze: ur40951965
    Bervi: ur24082448
    Rheya: ur18847773
    Name: ur26054226

imdbparser:
  frequency: 1200000
  delay: 10000

moviemetadata:
  frequency: 120000
  delay: 10000
