rtmUrl: https://slack.com/api/rtm.start?token={token}&simple_latest&no_unreads
logging.level.kotlin: DEBUG


spring:

  jpa.properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
        temp:
          use_jdbc_metadata_defaults: false

  datasource:
    url: ${jdbcUrl:redacted}
    username: ${jdbcUsername:redacted}
    password: ${jdbcPassword:redacted}
    driver-class-name: org.postgresql.Driver

logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled:
      show-details: always

feign:
  client:
    config:
      default:
        loggerLevel: full
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
    kombient: DEBUG
    org.springframework.transaction: trace
    kombient.movies.tmdb.TmdbClient: DEBUG

dns.health.hostnames: google.com,postgres

imdb:
  similarityscore: 0.85
  channel: '#secrettchannel'
  userconfig:
    Gweli: ur24140816
    Warc: ur24043276
    Tommy: ur36033733
    Molcsa: ur28253056
    Shank: ur32966271
    Eri: ur24012933
    Bensze: ur40951965
    Bervi: ur24082448
    Rheya: ur18847773
    Name: ur26054226

imdbparser:
  frequency: 1200000
  delay: 10000

