rtmUrl: https://slack.com/api/rtm.start?token={token}&simple_latest&no_unreads
logging.level.kotlin: DEBUG

spring:
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    url: redacted
    username: redacted
    password: redacted
    driver-class-name: org.postgresql.Driver

slackBotToken: redacted
omdbApiKey: redacted
tmdbApiKey: redacted
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
management:
  endpoints:
    web:
      expose:
        - info
        - health
  endpoint:
    health:
      show-details: true
  health:
    defaults: true
    enabled: true
    show-details: true
